### ISSUE TITLE
add linter integration for the 3D-network-viewer

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/3d-network-viewer#34]
As a developer, I want to rely on a linter, so that I can worry less, if at all, about the quality of the code formatting.

**Acceptance criteria**
- [ ] GH Action using linter
- [ ] passing all linter checks

**Comment by MalinAhlberg** [comment]
Ideas for guidelines on javascript syntax:
- when to use `const` and when to use `function`.
- guidelines for when to use nested functions

**Comment by nanjiangshu** [comment]
This issue seems to be duplicated with #604

**Comment by mihai-sysbio** [comment]
Are you sure? This is a different repo, and likely requires a different linting setup than the main repo.

**Comment by nanjiangshu** [comment]
Sorry that we missed it. Will clarify the issue.
