### ISSUE TITLE
code refactoring

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/3d-network-viewer#35]
As a developer, I want to refactor the current code, so that it is easier to understand and work with.

There is already a good structure in most of the files and the functions look quite clean. It would help to consider breaking the existing files, especially `met-atlas-viewer.js` into smaller files so they are more modular and easier to work with. It would be ideal if the PR description for such work includes a summary of the important changes.

**Comment by e0** [comment]
Relevant discussion: https://github.com/MetabolicAtlas/3d-network-viewer/pull/32#discussion_r677659860

**Comment by mihai-sysbio** [comment]
@e0 suggest somewhere a rename of the package to `network-viewer`.

**Comment by MalinAhlberg** [comment]
Discuss need of more documentation in PR.
