### ISSUE TITLE
Mac users cannot click on nodes

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/3d-network-viewer#59]
Clicking (both left and right clicks) on nodes does not work on certain Macs.

This used to be an obscure issue that only affected a specific MacBook but recently shown up in two newer MacBooks (both with the M1 chip). 

Message about potential work around: https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1144#issuecomment-1290165202

**Comment by mihai-sysbio** [comment]
This is an issue also for older Macs (Intel cpu). And it was was on and off - on the same machine it has both worked and not worked for the same machine.
